// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqymafnbwacpawcxwohe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxeW1hZm5id2FjcGF3Y3h3b2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMjc3ODUsImV4cCI6MjA2MzgwMzc4NX0.61mQ62yptDA5zJadtMcRPjdNnO5g5VqZfoJrtWODO94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});